/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Character_Soldier.gltf -o src/components/CharacterSoldier.jsx -r public -k
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useGraph } from "@react-three/fiber";
import React, { useEffect, useMemo, useRef } from "react";
import { Color, LoopOnce, MeshStandardMaterial } from "three";
import { SkeletonUtils } from "three-stdlib";
import { WEAPONS } from "./Experience";

export function CharacterSoldier({
  color = "black",
  animation = "Idle",
  weapon = "AK",
  ...props
}) {
  const group = useRef();
  const { scene, materials, animations } = useGLTF(
    "/models/Character_Soldier.gltf",
  );
  // Skinned meshes cannot be re-used in threejs without cloning them
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  // useGraph creates two flat object collections for nodes and materials
  const { nodes } = useGraph(clone);
  const { actions } = useAnimations(animations, group);
  if (actions["Death"]) {
    actions["Death"].loop = LoopOnce;
    actions["Death"].clampWhenFinished = true;
  }

  useEffect(() => {
    actions[animation].reset().fadeIn(0.2).play();
    return () => actions[animation]?.fadeOut(0.2);
  }, [animation]);

  const playerColorMaterial = useMemo(
    () =>
      new MeshStandardMaterial({
        color: new Color(color),
      }),
    [color],
  );

  // Christmas-themed materials
  const santaRedMaterial = useMemo(
    () =>
      new MeshStandardMaterial({
        color: new Color("#C41E3A"), // Santa red
      }),
    [],
  );

  const whiteTrimMaterial = useMemo(
    () =>
      new MeshStandardMaterial({
        color: new Color("#FFFFFF"), // White fur trim
      }),
    [],
  );

  const blackMaterial = useMemo(
    () =>
      new MeshStandardMaterial({
        color: new Color("#1a1a1a"), // Black boots/belt
      }),
    [],
  );

  useEffect(() => {
    // HIDING NON-SELECTED WEAPONS
    WEAPONS.forEach((wp) => {
      const isCurrentWeapon = wp === weapon;
      nodes[wp].visible = isCurrentWeapon;
    });

    // ASSIGNING CHARACTER COLOR
    nodes.Body.traverse((child) => {
      if (child.isMesh && child.material.name === "Character_Main") {
        child.material = playerColorMaterial;
      }
      if (child.isMesh) {
        child.castShadow = true;
        child.receiveShadow = true;
      }
    });
    // Apply materials to Head for Santa look
    if (nodes.Head) {
      nodes.Head.traverse((child) => {
        if (child.isMesh) {
          if (child.material.name === "Character_Main") {
            child.material = santaRedMaterial;
          } else if (child.material.name === "Grey") {
            // Make the hat/helmet red for Santa
            child.material = playerColorMaterial;
          } else if (child.material.name === "Black") {
            child.material = blackMaterial;
          }
        }
      });
    }

    // Apply materials to ShoulderPads for Christmas look
    if (nodes.ShoulderPadL) {
      nodes.ShoulderPadL.traverse((child) => {
        if (child.isMesh && child.material.name === "Grey") {
          child.material = whiteTrimMaterial;
          child.castShadow = true;
        }
      });
    }

    if (nodes.ShoulderR) {
      nodes.ShoulderR.traverse((child) => {
        if (child.isMesh && child.material.name === "Grey") {
          child.material = whiteTrimMaterial;
          child.castShadow = true;
        }
      });
    }

    clone.traverse((child) => {
      if (child.isMesh && child.material.name === "Character_Main") {
        child.material = playerColorMaterial;
      }
      if (child.isMesh) {
        child.castShadow = true;
      }
    });
  }, [
    nodes,
    clone,
    playerColorMaterial,
    santaRedMaterial,
    whiteTrimMaterial,
    blackMaterial,
  ]);

  return (
    <group {...props} dispose={null} ref={group}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <group name="Body_1">
            <skinnedMesh
              name="Cube004"
              geometry={nodes.Cube004.geometry}
              material={materials.Skin}
              skeleton={nodes.Cube004.skeleton}
              castShadow
            />
            <skinnedMesh
              name="Cube004_1"
              geometry={nodes.Cube004_1.geometry}
              material={whiteTrimMaterial}
              skeleton={nodes.Cube004_1.skeleton}
              castShadow
            />
            <skinnedMesh
              name="Cube004_2"
              geometry={nodes.Cube004_2.geometry}
              material={santaRedMaterial}
              skeleton={nodes.Cube004_2.skeleton}
              castShadow
            />
            <skinnedMesh
              name="Cube004_3"
              geometry={nodes.Cube004_3.geometry}
              material={santaRedMaterial}
              skeleton={nodes.Cube004_3.skeleton}
              castShadow
            />
            <skinnedMesh
              name="Cube004_4"
              geometry={nodes.Cube004_4.geometry}
              material={blackMaterial}
              skeleton={nodes.Cube004_4.skeleton}
              castShadow
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Character_Soldier.gltf");
