/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/grave.glb -o src/components/Grave.jsx -r public
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Grave({ color, ...props }) {
  const { nodes, materials } = useGLTF("/models/grave.glb");

  return (
    <group {...props} dispose={null} scale={0.5}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grave_A.geometry}
        material={materials.HalloweenBits}
      ></mesh>
      <mesh geometry={nodes.Plane.geometry} position={[0, 0, 1]} scale={0.5}>
        <meshBasicMaterial color={color || "#808080"} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/grave.glb");
